### ISSUE TITLE
Does It Work On Thunkable or MIT App Inventor

### ISSUE THREAD

**Issue by ghost** [alexa/AIAClientSDK#2]
Is the .aia file avalible for using it on x.thunkable.com

**Comment by kencecka** [comment]
Hi @Devaansh-Pathak,

This SDK provides C source code for connecting to the [AVS Integration for AWS IoT (AIA for short) service](https://docs.aws.amazon.com/iot/latest/developerguide/avs-integration-aws-iot.html), a lightweight interface for interfacing to Alexa.  We do not currently have any pre-built versions for use in environments like Thunkable or MIT App Inventor.

From a quick review, it looks like MIT App Inventor uses the suffix `.aia` for its application files, but that is a coincidence, and unrelated to this SDK.  If you are interested in connecting to Alexa in the MIT App Inventor, you could [look at existing projects to integrate it](https://www.google.com/search?q=mit+app+inventor+alexa), or port [one of our SDKs](https://github.com/alexa) to an App Inventor extension.

Ken

**Comment by Devaansh-Pathak** [comment]
@kencecka  You are right
