### ISSUE TITLE
How AIA controls Ligth's switch？

### ISSUE THREAD

**Issue by mars9180** [alexa/AIAClientSDK#4]
Hello.whats should i can control the switch of light by voice when i run AIA on the light device.when i say:trun on the light.the device replied :The device not found，whats can i do in the next.Does the AIA support Alexa.Power controller interface?
thanks.

**Comment by 1cengizk** [comment]
Hi, supporting Smart Home functionality in AIA is a project we are actively working on.

Meanwhile, you can refer to the following in order to use Smart Home features through a 3P Alexa skill: https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html

**Comment by mars9180** [comment]
> Hi, supporting Smart Home functionality in AIA is a project we are actively working on.
> 
> Meanwhile, you can refer to the following in order to use Smart Home features through a 3P Alexa skill: https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html

Okay， thanks
